[phases.setup]
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "cd frontend && npm install",
    "cd backend && python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi --bind 0.0.0.0:$PORT"
