[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/v1/employees/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
